### ISSUE TITLE
Requires version 7.4 of Vim

### ISSUE THREAD

**Issue by ts95** [timss/vimconf#11]
You should add to the readme that version 7.4 is required in order for all of the plugins to work.
```bash
$ vim --version | head -n 1 | grep "\d\.\d"
```

**Comment by timss** [comment]
It would probably be better to check which version of Vim you're running when a plugin is loaded, and decide if it should be used or not. For example, or vim-startify is the issue, it could be done in the following fashion:

    if v:version >= 704
        Plugin 'mhinz/vim-startify'
    endif

Or where it makes sense, check if the necessary functionality is available in the current version of vim:

    if has('persistent_undo')
        set ...
    endif

One major drawback with this is that it requires more maintainence. I will look more into it later, but thanks for bringing it up as it is probably relevant for quite a few users.

**Comment by timss** [comment]
Relevant issue: https://github.com/mhinz/vim-startify/issues/183

**Comment by timss** [comment]
https://github.com/mhinz/vim-startify/issues/183 fixed in https://github.com/mhinz/vim-startify/commit/b81dfa54b979aac27179fe0583c2b92f04c8ddad

Thanks for pointing it out @ts95, and thanks to @mhinz for a quick resolution.
