### ISSUE TITLE
FileType of sh for *.txt

### ISSUE THREAD

**Issue by eric-bixby** [timss/vimconf#14]
https://github.com/timss/vimconf/blob/6ef3d9e4cf64b3ffe5f38a6a3ea49985eddde07e/.vimrc#L139

On line 139 you are setting the FileType to shell for text files.

I've overridden/corrected this in my .vimrc.last file, but just curious why are you doing that?

**Comment by timss** [comment]
Hi! Good catch, this probably shouldn't be included in vimconf, but something I'll move to my own personal `.vimrc.last` in https://github.com/timss/dotfiles 👍 I've had this filetype association forever since I usually use `.txt` for simple notes etc.

**Comment by eric-bixby** [comment]
Thanks!
