### ISSUE TITLE
E185: Cannot find color scheme 'jellybeans'

### ISSUE THREAD

**Issue by wow-meow-ai** [timss/vimconf#6]
$ cd ~/.vim
$ git clone https://github.com/timss/vimconf.git
$ cd ~
$ ln  -s  ~/.vim/vimconf/.vimrc  .vimrc
$ vim

Error detected while processing /home/gund/.vimrc:
line  115:
E185: Cannot find color scheme 'jellybeans'
Press ENTER or type command to continue

---

Thanks in advance!

with regards,
gundamlh

**Comment by SalimF** [comment]
For latest version the color scheme folder located here 
`~/.config/nvim/colors/`

**Comment by timss** [comment]
@SalimF That's Neovim specific, not really "latest version" of Vim per se.
