### ISSUE TITLE
lightline with syntactic

### ISSUE THREAD

**Issue by bounceme** [timss/vimconf#9]
the syntactic section of the status line isn't updating unless i switch files first, I've used your lightline settings and slightly modified them,they were really helpful since i wanted to have buffer line integrated also, but this is my only problem.
here is my vimdc
https://github.com/bounceme/edits/blob/master/.vimrc

**Comment by timss** [comment]
Thanks for reporting this issue. 

I'm not sure if I understood you correctly, but this is not the behaviour you're seeing?

http://i.imgur.com/t40GIB7.gif

I haven't personally been a heavy user of Syntastic for a while, so there might be something I haven't noticed, but from your description it seems that it shouldn't work with just a `:wq` after an error has been detected? 

Could it be that it's whatever syntax checker you're using that is having issues, or even Syntastic having problems communicating the changes?

**Comment by bounceme** [comment]
I have syntastic set to show errors when the file is open or saved,the syntactic component isn't updating unless I switch to another file and then back to the file in question,either for reporting an error or when it should be fixed and not showing.this might be something to do with my setup or the settings for the lighten component but it seems to work for you.
this is happening with jshint and htmltidy

**Comment by timss** [comment]
I see.

I'll take a better look at it when I get the time, hopefully tomorrow.

**Comment by bounceme** [comment]
I found what was happening,you have to add all the filetypes you want here in the lightline settings
autocmd BufWritePost *.c,*.cpp,*.perl,*py call s:syntastic()

sorry this was basically nothing.

**Comment by timss** [comment]
Ah, right. 

I'm not sure if that part could be done more intuitively, without just adding tons of programming langauges that covers everything Syntastic is able to do. This is not a good solution, but for now users of vimconf is expected to override the function itself in `.vimrc.last`. 

Maybe I can define the `g:syntastic_mode_map` earlier in the file and use it in the lightline configuration some way, would be make it easier to maintain and change if nothing else.

**Comment by timss** [comment]
Made it somewhat easier to configure, now only required to change `g:syntastic_mode_map` and lightline will respect that setting. However overriding it in `.vimrc.last` does not work, so it's still suboptimal.

Leaving this open until I've figured out a better solution, as it now requires any user to edit the main `.vimrc`.

**Comment by timss** [comment]
https://github.com/timss/vimconf/commit/27554fb9dacfbdb6610760dd5bba351d6b2e8967
